"""brands

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-12 22:28:13.223864
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('primary_language', sa.String(length=16), nullable=False),
    sa.Column('business_model', sa.String(length=64), nullable=True),
    sa.Column('risk_category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=False)
    op.create_index(op.f('ix_brands_tenant_id'), 'brands', ['tenant_id'], unique=False)
    op.create_table('brand_audiences',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocabulary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_audiences_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_audiences'))
    )
    op.create_index(op.f('ix_brand_audiences_brand_id'), 'brand_audiences', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_audiences_tenant_id'), 'brand_audiences', ['tenant_id'], unique=False)
    op.create_table('brand_claims',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('is_prohibited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_claims_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_claims'))
    )
    op.create_index(op.f('ix_brand_claims_brand_id'), 'brand_claims', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_claims_tenant_id'), 'brand_claims', ['tenant_id'], unique=False)
    op.create_table('brand_competitors',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('competitor_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('discovered_via', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_competitors_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_competitors'))
    )
    op.create_index(op.f('ix_brand_competitors_brand_id'), 'brand_competitors', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_competitors_domain'), 'brand_competitors', ['domain'], unique=False)
    op.create_index(op.f('ix_brand_competitors_tenant_id'), 'brand_competitors', ['tenant_id'], unique=False)
    op.create_table('brand_goals',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_metric', sa.String(length=120), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_goals_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_goals'))
    )
    op.create_index(op.f('ix_brand_goals_brand_id'), 'brand_goals', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_goals_tenant_id'), 'brand_goals', ['tenant_id'], unique=False)
    op.create_table('brand_locations',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postcode', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('service_area', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('landing_url', sa.String(length=500), nullable=True),
    sa.Column('gbp_location_id', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_locations_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_locations'))
    )
    op.create_index(op.f('ix_brand_locations_brand_id'), 'brand_locations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_locations_tenant_id'), 'brand_locations', ['tenant_id'], unique=False)
    op.create_table('brand_products',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('landing_url', sa.String(length=500), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_products_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_products'))
    )
    op.create_index(op.f('ix_brand_products_brand_id'), 'brand_products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_products_tenant_id'), 'brand_products', ['tenant_id'], unique=False)
    op.create_table('brand_services',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('landing_url', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('revenue_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_services_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_services'))
    )
    op.create_index(op.f('ix_brand_services_brand_id'), 'brand_services', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_services_tenant_id'), 'brand_services', ['tenant_id'], unique=False)
    op.create_table('brand_voice_profiles',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('reading_level', sa.String(length=64), nullable=True),
    sa.Column('person', sa.String(length=32), nullable=True),
    sa.Column('approved_terminology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forbidden_terminology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_voice_profiles_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_voice_profiles'))
    )
    op.create_index(op.f('ix_brand_voice_profiles_brand_id'), 'brand_voice_profiles', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_voice_profiles_tenant_id'), 'brand_voice_profiles', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_projects_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_brand_id'), 'projects', ['brand_id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('competitor_observations',
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('observation_type', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['brand_competitors.id'], name=op.f('fk_competitor_observations_competitor_id_brand_competitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_observations'))
    )
    op.create_index(op.f('ix_competitor_observations_competitor_id'), 'competitor_observations', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_observations_tenant_id'), 'competitor_observations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_observations_tenant_id'), table_name='competitor_observations')
    op.drop_index(op.f('ix_competitor_observations_competitor_id'), table_name='competitor_observations')
    op.drop_table('competitor_observations')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_brand_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_brand_voice_profiles_tenant_id'), table_name='brand_voice_profiles')
    op.drop_index(op.f('ix_brand_voice_profiles_brand_id'), table_name='brand_voice_profiles')
    op.drop_table('brand_voice_profiles')
    op.drop_index(op.f('ix_brand_services_tenant_id'), table_name='brand_services')
    op.drop_index(op.f('ix_brand_services_brand_id'), table_name='brand_services')
    op.drop_table('brand_services')
    op.drop_index(op.f('ix_brand_products_tenant_id'), table_name='brand_products')
    op.drop_index(op.f('ix_brand_products_brand_id'), table_name='brand_products')
    op.drop_table('brand_products')
    op.drop_index(op.f('ix_brand_locations_tenant_id'), table_name='brand_locations')
    op.drop_index(op.f('ix_brand_locations_brand_id'), table_name='brand_locations')
    op.drop_table('brand_locations')
    op.drop_index(op.f('ix_brand_goals_tenant_id'), table_name='brand_goals')
    op.drop_index(op.f('ix_brand_goals_brand_id'), table_name='brand_goals')
    op.drop_table('brand_goals')
    op.drop_index(op.f('ix_brand_competitors_tenant_id'), table_name='brand_competitors')
    op.drop_index(op.f('ix_brand_competitors_domain'), table_name='brand_competitors')
    op.drop_index(op.f('ix_brand_competitors_brand_id'), table_name='brand_competitors')
    op.drop_table('brand_competitors')
    op.drop_index(op.f('ix_brand_claims_tenant_id'), table_name='brand_claims')
    op.drop_index(op.f('ix_brand_claims_brand_id'), table_name='brand_claims')
    op.drop_table('brand_claims')
    op.drop_index(op.f('ix_brand_audiences_tenant_id'), table_name='brand_audiences')
    op.drop_index(op.f('ix_brand_audiences_brand_id'), table_name='brand_audiences')
    op.drop_table('brand_audiences')
    op.drop_index(op.f('ix_brands_tenant_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
