"""websites

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-12 22:28:16.220053
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_scorecards',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('pages_evaluated', sa.Integer(), nullable=False),
    sa.Column('issues_total', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_scorecards'))
    )
    op.create_index(op.f('ix_website_scorecards_brand_id'), 'website_scorecards', ['brand_id'], unique=False)
    op.create_index(op.f('ix_website_scorecards_tenant_id'), 'website_scorecards', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_website_scorecards_website_id'), 'website_scorecards', ['website_id'], unique=False)
    op.create_table('websites',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('base_path', sa.String(length=255), nullable=False),
    sa.Column('cms', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('crawl_frequency', sa.String(length=32), nullable=False),
    sa.Column('robots_url', sa.String(length=500), nullable=True),
    sa.Column('sitemap_url', sa.String(length=500), nullable=True),
    sa.Column('crawl_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_websites_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_websites')),
    sa.UniqueConstraint('brand_id', 'domain', name='uq_websites_brand_domain')
    )
    op.create_index(op.f('ix_websites_brand_id'), 'websites', ['brand_id'], unique=False)
    op.create_index(op.f('ix_websites_tenant_id'), 'websites', ['tenant_id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('robots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sitemap_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('stopped_reason', sa.String(length=200), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_crawl_jobs_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_jobs'))
    )
    op.create_index(op.f('ix_crawl_jobs_brand_id'), 'crawl_jobs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_tenant_id'), 'crawl_jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_website_id'), 'crawl_jobs', ['website_id'], unique=False)
    op.create_table('pages',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('indexability', sa.String(length=32), nullable=False),
    sa.Column('indexability_reason', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_robots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hreflang', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('internal_links_out', sa.Integer(), nullable=False),
    sa.Column('internal_links_in', sa.Integer(), nullable=False),
    sa.Column('external_links_out', sa.Integer(), nullable=False),
    sa.Column('is_orphan', sa.Boolean(), nullable=False),
    sa.Column('in_sitemap', sa.Boolean(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('is_untrusted_external_content', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_pages_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('website_id', 'url', name='uq_pages_website_url')
    )
    op.create_index(op.f('ix_pages_brand_id'), 'pages', ['brand_id'], unique=False)
    op.create_index(op.f('ix_pages_tenant_id'), 'pages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pages_website_id'), 'pages', ['website_id'], unique=False)
    op.create_table('crawl_pages',
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('discovered_from', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('html_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_extract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('is_untrusted_external_content', sa.Boolean(), nullable=False),
    sa.Column('injection_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], name=op.f('fk_crawl_pages_crawl_job_id_crawl_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_pages'))
    )
    op.create_index(op.f('ix_crawl_pages_crawl_job_id'), 'crawl_pages', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_tenant_id'), 'crawl_pages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_website_id'), 'crawl_pages', ['website_id'], unique=False)
    op.create_table('page_images',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('has_alt', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('loading', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_images_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_images'))
    )
    op.create_index(op.f('ix_page_images_page_id'), 'page_images', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_images_tenant_id'), 'page_images', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_page_images_website_id'), 'page_images', ['website_id'], unique=False)
    op.create_table('page_issues',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('check_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_issues_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_issues'))
    )
    op.create_index(op.f('ix_page_issues_check_id'), 'page_issues', ['check_id'], unique=False)
    op.create_index(op.f('ix_page_issues_crawl_job_id'), 'page_issues', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_page_issues_dimension'), 'page_issues', ['dimension'], unique=False)
    op.create_index(op.f('ix_page_issues_page_id'), 'page_issues', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_issues_severity'), 'page_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_page_issues_status'), 'page_issues', ['status'], unique=False)
    op.create_index(op.f('ix_page_issues_tenant_id'), 'page_issues', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_page_issues_website_id'), 'page_issues', ['website_id'], unique=False)
    op.create_table('page_links',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=True),
    sa.Column('source_page_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=False),
    sa.Column('rel', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_broken', sa.Boolean(), nullable=False),
    sa.Column('target_status_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], name=op.f('fk_page_links_source_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_links'))
    )
    op.create_index(op.f('ix_page_links_source_page_id'), 'page_links', ['source_page_id'], unique=False)
    op.create_index(op.f('ix_page_links_tenant_id'), 'page_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_page_links_website_id'), 'page_links', ['website_id'], unique=False)
    op.create_table('page_schema',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('schema_type', sa.String(length=120), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_schema_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_schema'))
    )
    op.create_index(op.f('ix_page_schema_page_id'), 'page_schema', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_schema_tenant_id'), 'page_schema', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_page_schema_website_id'), 'page_schema', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_schema_website_id'), table_name='page_schema')
    op.drop_index(op.f('ix_page_schema_tenant_id'), table_name='page_schema')
    op.drop_index(op.f('ix_page_schema_page_id'), table_name='page_schema')
    op.drop_table('page_schema')
    op.drop_index(op.f('ix_page_links_website_id'), table_name='page_links')
    op.drop_index(op.f('ix_page_links_tenant_id'), table_name='page_links')
    op.drop_index(op.f('ix_page_links_source_page_id'), table_name='page_links')
    op.drop_table('page_links')
    op.drop_index(op.f('ix_page_issues_website_id'), table_name='page_issues')
    op.drop_index(op.f('ix_page_issues_tenant_id'), table_name='page_issues')
    op.drop_index(op.f('ix_page_issues_status'), table_name='page_issues')
    op.drop_index(op.f('ix_page_issues_severity'), table_name='page_issues')
    op.drop_index(op.f('ix_page_issues_page_id'), table_name='page_issues')
    op.drop_index(op.f('ix_page_issues_dimension'), table_name='page_issues')
    op.drop_index(op.f('ix_page_issues_crawl_job_id'), table_name='page_issues')
    op.drop_index(op.f('ix_page_issues_check_id'), table_name='page_issues')
    op.drop_table('page_issues')
    op.drop_index(op.f('ix_page_images_website_id'), table_name='page_images')
    op.drop_index(op.f('ix_page_images_tenant_id'), table_name='page_images')
    op.drop_index(op.f('ix_page_images_page_id'), table_name='page_images')
    op.drop_table('page_images')
    op.drop_index(op.f('ix_crawl_pages_website_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_tenant_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_crawl_job_id'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    op.drop_index(op.f('ix_pages_website_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_tenant_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_brand_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_crawl_jobs_website_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_tenant_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_brand_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_websites_tenant_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_brand_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_website_scorecards_website_id'), table_name='website_scorecards')
    op.drop_index(op.f('ix_website_scorecards_tenant_id'), table_name='website_scorecards')
    op.drop_index(op.f('ix_website_scorecards_brand_id'), table_name='website_scorecards')
    op.drop_table('website_scorecards')
    # ### end Alembic commands ###
