"""search

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-15 13:36:37.941994
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_questions',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalised', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answered_by_url', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_questions'))
    )
    op.create_index(op.f('ix_search_questions_brand_id'), 'search_questions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_search_questions_normalised'), 'search_questions', ['normalised'], unique=False)
    op.create_index(op.f('ix_search_questions_tenant_id'), 'search_questions', ['tenant_id'], unique=False)
    op.create_table('serp_snapshots',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_snapshots'))
    )
    op.create_index(op.f('ix_serp_snapshots_brand_id'), 'serp_snapshots', ['brand_id'], unique=False)
    op.create_index(op.f('ix_serp_snapshots_query'), 'serp_snapshots', ['query'], unique=False)
    op.create_index(op.f('ix_serp_snapshots_tenant_id'), 'serp_snapshots', ['tenant_id'], unique=False)
    op.create_table('keyword_clusters',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('head_keyword', sa.Text(), nullable=False),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keyword_count', sa.Integer(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('mapped_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_decision', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_keyword_clusters_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_clusters'))
    )
    op.create_index(op.f('ix_keyword_clusters_brand_id'), 'keyword_clusters', ['brand_id'], unique=False)
    op.create_index(op.f('ix_keyword_clusters_tenant_id'), 'keyword_clusters', ['tenant_id'], unique=False)
    op.create_table('serp_results',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('result_type', sa.String(length=64), nullable=False),
    sa.Column('is_brand', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['serp_snapshots.id'], name=op.f('fk_serp_results_snapshot_id_serp_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serp_results'))
    )
    op.create_index(op.f('ix_serp_results_domain'), 'serp_results', ['domain'], unique=False)
    op.create_index(op.f('ix_serp_results_snapshot_id'), 'serp_results', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_serp_results_tenant_id'), 'serp_results', ['tenant_id'], unique=False)
    op.create_table('keywords',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('normalised', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('is_branded', sa.Boolean(), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('is_question', sa.Boolean(), nullable=False),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_intent', sa.String(length=32), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('mapped_url', sa.Text(), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_keywords_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['keyword_clusters.id'], name=op.f('fk_keywords_cluster_id_keyword_clusters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('brand_id', 'normalised', 'country', name='uq_keywords_brand_norm')
    )
    op.create_index(op.f('ix_keywords_brand_id'), 'keywords', ['brand_id'], unique=False)
    op.create_index(op.f('ix_keywords_cluster_id'), 'keywords', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_keywords_normalised'), 'keywords', ['normalised'], unique=False)
    op.create_index(op.f('ix_keywords_opportunity_score'), 'keywords', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_keywords_primary_intent'), 'keywords', ['primary_intent'], unique=False)
    op.create_index(op.f('ix_keywords_tenant_id'), 'keywords', ['tenant_id'], unique=False)
    op.create_table('keyword_metrics',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_metrics_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_metrics'))
    )
    op.create_index(op.f('ix_keyword_metrics_keyword_id'), 'keyword_metrics', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_metric_name'), 'keyword_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_tenant_id'), 'keyword_metrics', ['tenant_id'], unique=False)
    op.create_table('keyword_rankings',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('device', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('search_engine', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_rankings_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_rankings'))
    )
    op.create_index(op.f('ix_keyword_rankings_keyword_id'), 'keyword_rankings', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_rankings_tenant_id'), 'keyword_rankings', ['tenant_id'], unique=False)
    op.create_table('keyword_variants',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('variant_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_variants_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_variants'))
    )
    op.create_index(op.f('ix_keyword_variants_keyword_id'), 'keyword_variants', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_variants_tenant_id'), 'keyword_variants', ['tenant_id'], unique=False)
    op.create_table('search_intents',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_intent', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classifier', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_search_intents_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_intents'))
    )
    op.create_index(op.f('ix_search_intents_keyword_id'), 'search_intents', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_search_intents_tenant_id'), 'search_intents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_intents_tenant_id'), table_name='search_intents')
    op.drop_index(op.f('ix_search_intents_keyword_id'), table_name='search_intents')
    op.drop_table('search_intents')
    op.drop_index(op.f('ix_keyword_variants_tenant_id'), table_name='keyword_variants')
    op.drop_index(op.f('ix_keyword_variants_keyword_id'), table_name='keyword_variants')
    op.drop_table('keyword_variants')
    op.drop_index(op.f('ix_keyword_rankings_tenant_id'), table_name='keyword_rankings')
    op.drop_index(op.f('ix_keyword_rankings_keyword_id'), table_name='keyword_rankings')
    op.drop_table('keyword_rankings')
    op.drop_index(op.f('ix_keyword_metrics_tenant_id'), table_name='keyword_metrics')
    op.drop_index(op.f('ix_keyword_metrics_metric_name'), table_name='keyword_metrics')
    op.drop_index(op.f('ix_keyword_metrics_keyword_id'), table_name='keyword_metrics')
    op.drop_table('keyword_metrics')
    op.drop_index(op.f('ix_keywords_tenant_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_primary_intent'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_opportunity_score'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_normalised'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_cluster_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_brand_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_serp_results_tenant_id'), table_name='serp_results')
    op.drop_index(op.f('ix_serp_results_snapshot_id'), table_name='serp_results')
    op.drop_index(op.f('ix_serp_results_domain'), table_name='serp_results')
    op.drop_table('serp_results')
    op.drop_index(op.f('ix_keyword_clusters_tenant_id'), table_name='keyword_clusters')
    op.drop_index(op.f('ix_keyword_clusters_brand_id'), table_name='keyword_clusters')
    op.drop_table('keyword_clusters')
    op.drop_index(op.f('ix_serp_snapshots_tenant_id'), table_name='serp_snapshots')
    op.drop_index(op.f('ix_serp_snapshots_query'), table_name='serp_snapshots')
    op.drop_index(op.f('ix_serp_snapshots_brand_id'), table_name='serp_snapshots')
    op.drop_table('serp_snapshots')
    op.drop_index(op.f('ix_search_questions_tenant_id'), table_name='search_questions')
    op.drop_index(op.f('ix_search_questions_normalised'), table_name='search_questions')
    op.drop_index(op.f('ix_search_questions_brand_id'), table_name='search_questions')
    op.drop_table('search_questions')
    # ### end Alembic commands ###
