"""content

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-15 13:36:40.969216
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_briefs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('content_asset_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_agent', sa.String(length=32), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_briefs'))
    )
    op.create_index(op.f('ix_content_briefs_brand_id'), 'content_briefs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_tenant_id'), 'content_briefs', ['tenant_id'], unique=False)
    op.create_table('content_research',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitor_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_agent', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_research'))
    )
    op.create_index(op.f('ix_content_research_brand_id'), 'content_research', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_research_tenant_id'), 'content_research', ['tenant_id'], unique=False)
    op.create_table('content_sources',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=True),
    sa.Column('content_asset_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('supports_claim', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_sources'))
    )
    op.create_index(op.f('ix_content_sources_brand_id'), 'content_sources', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_sources_tenant_id'), 'content_sources', ['tenant_id'], unique=False)
    op.create_table('content_assets',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_category', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('primary_keyword', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('canonical_source_asset_id', sa.UUID(), nullable=True),
    sa.Column('external_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_content_assets_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_assets'))
    )
    op.create_index(op.f('ix_content_assets_brand_id'), 'content_assets', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_assets_tenant_id'), 'content_assets', ['tenant_id'], unique=False)
    op.create_table('content_evaluations',
    sa.Column('content_asset_id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_type', sa.String(length=64), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocking_failures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('evaluated_by_agent', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], name=op.f('fk_content_evaluations_content_asset_id_content_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_evaluations'))
    )
    op.create_index(op.f('ix_content_evaluations_content_asset_id'), 'content_evaluations', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_content_evaluations_tenant_id'), 'content_evaluations', ['tenant_id'], unique=False)
    op.create_table('content_repairs',
    sa.Column('content_asset_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('repair_type', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('resulting_version', sa.Integer(), nullable=True),
    sa.Column('performed_by_agent', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], name=op.f('fk_content_repairs_content_asset_id_content_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_repairs'))
    )
    op.create_index(op.f('ix_content_repairs_content_asset_id'), 'content_repairs', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_content_repairs_tenant_id'), 'content_repairs', ['tenant_id'], unique=False)
    op.create_table('content_representation',
    sa.Column('content_asset_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=False),
    sa.Column('tone', sa.String(length=120), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('canonical_source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], name=op.f('fk_content_representation_content_asset_id_content_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_representation'))
    )
    op.create_index(op.f('ix_content_representation_content_asset_id'), 'content_representation', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_content_representation_tenant_id'), 'content_representation', ['tenant_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('content_asset_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('synthesis_mode', sa.String(length=32), nullable=False),
    sa.Column('created_by_agent', sa.String(length=32), nullable=True),
    sa.Column('created_by_user', sa.UUID(), nullable=True),
    sa.Column('brief_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], name=op.f('fk_content_versions_content_asset_id_content_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_versions')),
    sa.UniqueConstraint('content_asset_id', 'version', name='uq_content_versions_asset_version')
    )
    op.create_index(op.f('ix_content_versions_content_asset_id'), 'content_versions', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_content_versions_tenant_id'), 'content_versions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_versions_tenant_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_content_asset_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_content_representation_tenant_id'), table_name='content_representation')
    op.drop_index(op.f('ix_content_representation_content_asset_id'), table_name='content_representation')
    op.drop_table('content_representation')
    op.drop_index(op.f('ix_content_repairs_tenant_id'), table_name='content_repairs')
    op.drop_index(op.f('ix_content_repairs_content_asset_id'), table_name='content_repairs')
    op.drop_table('content_repairs')
    op.drop_index(op.f('ix_content_evaluations_tenant_id'), table_name='content_evaluations')
    op.drop_index(op.f('ix_content_evaluations_content_asset_id'), table_name='content_evaluations')
    op.drop_table('content_evaluations')
    op.drop_index(op.f('ix_content_assets_tenant_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_brand_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_content_sources_tenant_id'), table_name='content_sources')
    op.drop_index(op.f('ix_content_sources_brand_id'), table_name='content_sources')
    op.drop_table('content_sources')
    op.drop_index(op.f('ix_content_research_tenant_id'), table_name='content_research')
    op.drop_index(op.f('ix_content_research_brand_id'), table_name='content_research')
    op.drop_table('content_research')
    op.drop_index(op.f('ix_content_briefs_tenant_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_brand_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    # ### end Alembic commands ###
