"""agents

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-12 22:28:24.885188
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_capabilities',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_capabilities')),
    sa.UniqueConstraint('agent_id', 'capability', name='uq_agent_capabilities_agent_capability')
    )
    op.create_index(op.f('ix_agent_capabilities_agent_id'), 'agent_capabilities', ['agent_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('synthesis_mode', sa.String(length=32), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('security_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_brand_id'), 'agent_runs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_correlation_id'), 'agent_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_mission_id'), 'agent_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tools')),
    sa.UniqueConstraint('agent_id', 'tool', name='uq_agent_tools_agent_tool')
    )
    op.create_index(op.f('ix_agent_tools_agent_id'), 'agent_tools', ['agent_id'], unique=False)
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('model_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('agent_id', name='uq_agents_agent_id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('prompt_key', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index(op.f('ix_llm_usage_agent_id'), 'llm_usage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_provider'), 'llm_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_usage_tenant_id'), 'llm_usage', ['tenant_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_untrusted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_messages_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index(op.f('ix_agent_messages_agent_run_id'), 'agent_messages', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_tenant_id'), 'agent_messages', ['tenant_id'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('output_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_name', sa.String(length=120), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_outputs_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_outputs'))
    )
    op.create_index(op.f('ix_agent_outputs_agent_run_id'), 'agent_outputs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_outputs_tenant_id'), 'agent_outputs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_outputs_tenant_id'), table_name='agent_outputs')
    op.drop_index(op.f('ix_agent_outputs_agent_run_id'), table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_index(op.f('ix_agent_messages_tenant_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_agent_run_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_llm_usage_tenant_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_provider'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_agent_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_tools_agent_id'), table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_mission_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_correlation_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_brand_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_capabilities_agent_id'), table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    # ### end Alembic commands ###
