"""memory

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-15 13:36:48.739845
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_nodes')),
    sa.UniqueConstraint('tenant_id', 'node_type', 'key', name='uq_knowledge_nodes_key')
    )
    op.create_index(op.f('ix_knowledge_nodes_brand_id'), 'knowledge_nodes', ['brand_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_node_type'), 'knowledge_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_tenant_id'), 'knowledge_nodes', ['tenant_id'], unique=False)
    op.create_table('memories',
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_agent_id', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forgotten_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_brand_id'), 'memories', ['brand_id'], unique=False)
    op.create_index(op.f('ix_memories_is_active'), 'memories', ['is_active'], unique=False)
    op.create_index(op.f('ix_memories_key'), 'memories', ['key'], unique=False)
    op.create_index(op.f('ix_memories_memory_type'), 'memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memories_mission_id'), 'memories', ['mission_id'], unique=False)
    op.create_index(op.f('ix_memories_scope'), 'memories', ['scope'], unique=False)
    op.create_index(op.f('ix_memories_tenant_id'), 'memories', ['tenant_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], name=op.f('fk_knowledge_edges_source_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], name=op.f('fk_knowledge_edges_target_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_edges'))
    )
    op.create_index(op.f('ix_knowledge_edges_relationship'), 'knowledge_edges', ['relationship'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_source_node_id'), 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_node_id'), 'knowledge_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_tenant_id'), 'knowledge_edges', ['tenant_id'], unique=False)
    op.create_table('memory_embeddings',
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_memory_embeddings_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_embeddings')),
    sa.UniqueConstraint('memory_id', 'model', name='uq_memory_embeddings_model')
    )
    op.create_index(op.f('ix_memory_embeddings_memory_id'), 'memory_embeddings', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_embeddings_tenant_id'), 'memory_embeddings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_embeddings_tenant_id'), table_name='memory_embeddings')
    op.drop_index(op.f('ix_memory_embeddings_memory_id'), table_name='memory_embeddings')
    op.drop_table('memory_embeddings')
    op.drop_index(op.f('ix_knowledge_edges_tenant_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_target_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_relationship'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_memories_tenant_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_scope'), table_name='memories')
    op.drop_index(op.f('ix_memories_mission_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_memory_type'), table_name='memories')
    op.drop_index(op.f('ix_memories_key'), table_name='memories')
    op.drop_index(op.f('ix_memories_is_active'), table_name='memories')
    op.drop_index(op.f('ix_memories_brand_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_knowledge_nodes_tenant_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_node_type'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_brand_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
