"""decision

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-12 22:28:34.100073
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('source_tier', sa.String(length=32), nullable=True),
    sa.Column('is_observation', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('tenant_id', 'ref', name='uq_evidence_tenant_ref')
    )
    op.create_index(op.f('ix_evidence_brand_id'), 'evidence', ['brand_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_ref'), 'evidence', ['ref'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    op.create_table('experiments',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('control', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variant', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metric', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_brand_id'), 'experiments', ['brand_id'], unique=False)
    op.create_index(op.f('ix_experiments_tenant_id'), 'experiments', ['tenant_id'], unique=False)
    op.create_table('policies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_threshold', sa.String(length=32), nullable=False),
    sa.Column('approval_mode', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_policies_tenant_name')
    )
    op.create_index(op.f('ix_policies_scope'), 'policies', ['scope'], unique=False)
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    op.create_table('evidence_relationships',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_evidence_relationships_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_relationships'))
    )
    op.create_index(op.f('ix_evidence_relationships_entity_id'), 'evidence_relationships', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_relationships_entity_type'), 'evidence_relationships', ['entity_type'], unique=False)
    op.create_index(op.f('ix_evidence_relationships_evidence_id'), 'evidence_relationships', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_relationships_tenant_id'), 'evidence_relationships', ['tenant_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=True),
    sa.Column('target_entity_id', sa.String(length=200), nullable=True),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Float(), nullable=False),
    sa.Column('seo_impact', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('effort', sa.Float(), nullable=False),
    sa.Column('strategic_fit', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_by_agent', sa.String(length=32), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_opportunities_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_brand_id'), 'opportunities', ['brand_id'], unique=False)
    op.create_index(op.f('ix_opportunities_mission_id'), 'opportunities', ['mission_id'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_priority_score'), 'opportunities', ['priority_score'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_tenant_id'), 'opportunities', ['tenant_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('recommendation_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('opportunity_statement', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Float(), nullable=False),
    sa.Column('seo_impact', sa.Float(), nullable=False),
    sa.Column('effort', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('strategic_fit', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=True),
    sa.Column('target_entity_id', sa.String(length=200), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('deferred_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_recommendations_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_recommendations_opportunity_id_opportunities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_brand_id'), 'recommendations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_recommendations_mission_id'), 'recommendations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_recommendations_priority_score'), 'recommendations', ['priority_score'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_tenant_id'), 'recommendations', ['tenant_id'], unique=False)
    op.create_table('actions',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('executor_agent_id', sa.String(length=32), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('policy_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('integration_mode', sa.String(length=32), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_actions_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_actions_recommendation_id_recommendations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_actions_idempotency')
    )
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_actions_brand_id'), 'actions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_actions_correlation_id'), 'actions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_actions_mission_id'), 'actions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_index(op.f('ix_actions_tenant_id'), 'actions', ['tenant_id'], unique=False)
    op.create_table('action_approvals',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_by_role', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_action_approvals_action_id_actions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_approvals'))
    )
    op.create_index(op.f('ix_action_approvals_action_id'), 'action_approvals', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_approvals_tenant_id'), 'action_approvals', ['tenant_id'], unique=False)
    op.create_table('action_outcomes',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=120), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('delta_percent', sa.Float(), nullable=True),
    sa.Column('measurement_window_days', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_action_outcomes_action_id_actions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_outcomes'))
    )
    op.create_index(op.f('ix_action_outcomes_action_id'), 'action_outcomes', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_outcomes_brand_id'), 'action_outcomes', ['brand_id'], unique=False)
    op.create_index(op.f('ix_action_outcomes_mission_id'), 'action_outcomes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_action_outcomes_tenant_id'), 'action_outcomes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_outcomes_tenant_id'), table_name='action_outcomes')
    op.drop_index(op.f('ix_action_outcomes_mission_id'), table_name='action_outcomes')
    op.drop_index(op.f('ix_action_outcomes_brand_id'), table_name='action_outcomes')
    op.drop_index(op.f('ix_action_outcomes_action_id'), table_name='action_outcomes')
    op.drop_table('action_outcomes')
    op.drop_index(op.f('ix_action_approvals_tenant_id'), table_name='action_approvals')
    op.drop_index(op.f('ix_action_approvals_action_id'), table_name='action_approvals')
    op.drop_table('action_approvals')
    op.drop_index(op.f('ix_actions_tenant_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_mission_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_correlation_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_brand_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_recommendations_tenant_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority_score'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_mission_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_brand_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_opportunities_tenant_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_priority_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_mission_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_brand_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_evidence_relationships_tenant_id'), table_name='evidence_relationships')
    op.drop_index(op.f('ix_evidence_relationships_evidence_id'), table_name='evidence_relationships')
    op.drop_index(op.f('ix_evidence_relationships_entity_type'), table_name='evidence_relationships')
    op.drop_index(op.f('ix_evidence_relationships_entity_id'), table_name='evidence_relationships')
    op.drop_table('evidence_relationships')
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_scope'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_experiments_tenant_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_brand_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_ref'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_brand_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
