"""integrations

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-12 22:28:37.134933
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ga4_conversions',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('session_default_channel_group', sa.String(length=120), nullable=True),
    sa.Column('event_count', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('event_value', sa.Float(), nullable=False),
    sa.Column('is_qualified_lead_event', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ga4_conversions'))
    )
    op.create_index(op.f('ix_ga4_conversions_brand_id'), 'ga4_conversions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ga4_conversions_date'), 'ga4_conversions', ['date'], unique=False)
    op.create_index(op.f('ix_ga4_conversions_event_name'), 'ga4_conversions', ['event_name'], unique=False)
    op.create_index(op.f('ix_ga4_conversions_tenant_id'), 'ga4_conversions', ['tenant_id'], unique=False)
    op.create_table('ga4_metrics',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('session_default_channel_group', sa.String(length=120), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('engaged_sessions', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('average_session_duration', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ga4_metrics'))
    )
    op.create_index(op.f('ix_ga4_metrics_brand_id'), 'ga4_metrics', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ga4_metrics_date'), 'ga4_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_ga4_metrics_tenant_id'), 'ga4_metrics', ['tenant_id'], unique=False)
    op.create_table('gsc_inspections',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('site_url', sa.String(length=500), nullable=False),
    sa.Column('inspected_url', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=64), nullable=True),
    sa.Column('coverage_state', sa.String(length=200), nullable=True),
    sa.Column('indexing_state', sa.String(length=120), nullable=True),
    sa.Column('robots_txt_state', sa.String(length=64), nullable=True),
    sa.Column('page_fetch_state', sa.String(length=64), nullable=True),
    sa.Column('google_canonical', sa.Text(), nullable=True),
    sa.Column('user_canonical', sa.Text(), nullable=True),
    sa.Column('last_crawl_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response_id', sa.UUID(), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsc_inspections'))
    )
    op.create_index(op.f('ix_gsc_inspections_brand_id'), 'gsc_inspections', ['brand_id'], unique=False)
    op.create_index(op.f('ix_gsc_inspections_inspected_url'), 'gsc_inspections', ['inspected_url'], unique=False)
    op.create_index(op.f('ix_gsc_inspections_tenant_id'), 'gsc_inspections', ['tenant_id'], unique=False)
    op.create_table('gsc_performance',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=True),
    sa.Column('site_url', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('page', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('search_appearance', sa.String(length=64), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsc_performance'))
    )
    op.create_index(op.f('ix_gsc_performance_brand_id'), 'gsc_performance', ['brand_id'], unique=False)
    op.create_index(op.f('ix_gsc_performance_date'), 'gsc_performance', ['date'], unique=False)
    op.create_index(op.f('ix_gsc_performance_tenant_id'), 'gsc_performance', ['tenant_id'], unique=False)
    op.create_table('gsc_sitemaps',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('site_url', sa.String(length=500), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sitemap_type', sa.String(length=64), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('is_sitemaps_index', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('submitted_urls', sa.Integer(), nullable=False),
    sa.Column('indexed_urls', sa.Integer(), nullable=True),
    sa.Column('last_submitted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_downloaded', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsc_sitemaps'))
    )
    op.create_index(op.f('ix_gsc_sitemaps_brand_id'), 'gsc_sitemaps', ['brand_id'], unique=False)
    op.create_index(op.f('ix_gsc_sitemaps_tenant_id'), 'gsc_sitemaps', ['tenant_id'], unique=False)
    op.create_table('provider_raw_responses',
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_raw_responses'))
    )
    op.create_index(op.f('ix_provider_raw_responses_provider'), 'provider_raw_responses', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_raw_responses_tenant_id'), 'provider_raw_responses', ['tenant_id'], unique=False)
    op.create_table('integration_connections',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_status', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_integration_connections_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_connections')),
    sa.UniqueConstraint('tenant_id', 'brand_id', 'provider', name='uq_integration_connections_scope')
    )
    op.create_index(op.f('ix_integration_connections_brand_id'), 'integration_connections', ['brand_id'], unique=False)
    op.create_index(op.f('ix_integration_connections_provider'), 'integration_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_connections_tenant_id'), 'integration_connections', ['tenant_id'], unique=False)
    op.create_table('ga4_connections',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('google_account_email', sa.String(length=320), nullable=True),
    sa.Column('selected_property_id', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_ga4_connections_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ga4_connections'))
    )
    op.create_index(op.f('ix_ga4_connections_brand_id'), 'ga4_connections', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ga4_connections_connection_id'), 'ga4_connections', ['connection_id'], unique=False)
    op.create_index(op.f('ix_ga4_connections_tenant_id'), 'ga4_connections', ['tenant_id'], unique=False)
    op.create_table('gsc_connections',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('google_account_email', sa.String(length=320), nullable=True),
    sa.Column('selected_property', sa.String(length=500), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_gsc_connections_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsc_connections'))
    )
    op.create_index(op.f('ix_gsc_connections_brand_id'), 'gsc_connections', ['brand_id'], unique=False)
    op.create_index(op.f('ix_gsc_connections_connection_id'), 'gsc_connections', ['connection_id'], unique=False)
    op.create_index(op.f('ix_gsc_connections_tenant_id'), 'gsc_connections', ['tenant_id'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('credential_ref', sa.String(length=200), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name=op.f('fk_integration_credentials_connection_id_integration_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_credentials'))
    )
    op.create_index(op.f('ix_integration_credentials_connection_id'), 'integration_credentials', ['connection_id'], unique=False)
    op.create_index(op.f('ix_integration_credentials_tenant_id'), 'integration_credentials', ['tenant_id'], unique=False)
    op.create_table('ga4_properties',
    sa.Column('ga4_connection_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('currency_code', sa.String(length=8), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ga4_connection_id'], ['ga4_connections.id'], name=op.f('fk_ga4_properties_ga4_connection_id_ga4_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ga4_properties')),
    sa.UniqueConstraint('ga4_connection_id', 'property_id', name='uq_ga4_properties_property')
    )
    op.create_index(op.f('ix_ga4_properties_ga4_connection_id'), 'ga4_properties', ['ga4_connection_id'], unique=False)
    op.create_index(op.f('ix_ga4_properties_tenant_id'), 'ga4_properties', ['tenant_id'], unique=False)
    op.create_table('gsc_properties',
    sa.Column('gsc_connection_id', sa.UUID(), nullable=False),
    sa.Column('site_url', sa.String(length=500), nullable=False),
    sa.Column('permission_level', sa.String(length=64), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['gsc_connection_id'], ['gsc_connections.id'], name=op.f('fk_gsc_properties_gsc_connection_id_gsc_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gsc_properties')),
    sa.UniqueConstraint('gsc_connection_id', 'site_url', name='uq_gsc_properties_site')
    )
    op.create_index(op.f('ix_gsc_properties_gsc_connection_id'), 'gsc_properties', ['gsc_connection_id'], unique=False)
    op.create_index(op.f('ix_gsc_properties_tenant_id'), 'gsc_properties', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsc_properties_tenant_id'), table_name='gsc_properties')
    op.drop_index(op.f('ix_gsc_properties_gsc_connection_id'), table_name='gsc_properties')
    op.drop_table('gsc_properties')
    op.drop_index(op.f('ix_ga4_properties_tenant_id'), table_name='ga4_properties')
    op.drop_index(op.f('ix_ga4_properties_ga4_connection_id'), table_name='ga4_properties')
    op.drop_table('ga4_properties')
    op.drop_index(op.f('ix_integration_credentials_tenant_id'), table_name='integration_credentials')
    op.drop_index(op.f('ix_integration_credentials_connection_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_gsc_connections_tenant_id'), table_name='gsc_connections')
    op.drop_index(op.f('ix_gsc_connections_connection_id'), table_name='gsc_connections')
    op.drop_index(op.f('ix_gsc_connections_brand_id'), table_name='gsc_connections')
    op.drop_table('gsc_connections')
    op.drop_index(op.f('ix_ga4_connections_tenant_id'), table_name='ga4_connections')
    op.drop_index(op.f('ix_ga4_connections_connection_id'), table_name='ga4_connections')
    op.drop_index(op.f('ix_ga4_connections_brand_id'), table_name='ga4_connections')
    op.drop_table('ga4_connections')
    op.drop_index(op.f('ix_integration_connections_tenant_id'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_provider'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_brand_id'), table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index(op.f('ix_provider_raw_responses_tenant_id'), table_name='provider_raw_responses')
    op.drop_index(op.f('ix_provider_raw_responses_provider'), table_name='provider_raw_responses')
    op.drop_table('provider_raw_responses')
    op.drop_index(op.f('ix_gsc_sitemaps_tenant_id'), table_name='gsc_sitemaps')
    op.drop_index(op.f('ix_gsc_sitemaps_brand_id'), table_name='gsc_sitemaps')
    op.drop_table('gsc_sitemaps')
    op.drop_index(op.f('ix_gsc_performance_tenant_id'), table_name='gsc_performance')
    op.drop_index(op.f('ix_gsc_performance_date'), table_name='gsc_performance')
    op.drop_index(op.f('ix_gsc_performance_brand_id'), table_name='gsc_performance')
    op.drop_table('gsc_performance')
    op.drop_index(op.f('ix_gsc_inspections_tenant_id'), table_name='gsc_inspections')
    op.drop_index(op.f('ix_gsc_inspections_inspected_url'), table_name='gsc_inspections')
    op.drop_index(op.f('ix_gsc_inspections_brand_id'), table_name='gsc_inspections')
    op.drop_table('gsc_inspections')
    op.drop_index(op.f('ix_ga4_metrics_tenant_id'), table_name='ga4_metrics')
    op.drop_index(op.f('ix_ga4_metrics_date'), table_name='ga4_metrics')
    op.drop_index(op.f('ix_ga4_metrics_brand_id'), table_name='ga4_metrics')
    op.drop_table('ga4_metrics')
    op.drop_index(op.f('ix_ga4_conversions_tenant_id'), table_name='ga4_conversions')
    op.drop_index(op.f('ix_ga4_conversions_event_name'), table_name='ga4_conversions')
    op.drop_index(op.f('ix_ga4_conversions_date'), table_name='ga4_conversions')
    op.drop_index(op.f('ix_ga4_conversions_brand_id'), table_name='ga4_conversions')
    op.drop_table('ga4_conversions')
    # ### end Alembic commands ###
