"""All ORM models.

Importing this package registers every table on ``Base.metadata`` — Alembic's
autogenerate and the test harness both depend on that.
"""

from __future__ import annotations

from seo_engine.domain.models.agents import (
    AgentCapabilityRecord,
    AgentMessage,
    AgentOutput,
    AgentRecord,
    AgentRun,
    AgentToolRecord,
    LLMUsage,
)
from seo_engine.domain.models.brand import (
    Brand,
    BrandAudience,
    BrandClaim,
    BrandCompetitor,
    BrandGoal,
    BrandLocation,
    BrandProduct,
    BrandService,
    BrandVoiceProfile,
    CompetitorObservation,
    Project,
)
from seo_engine.domain.models.content import (
    ContentAsset,
    ContentBriefRecord,
    ContentEvaluationRecord,
    ContentRepair,
    ContentRepresentation,
    ContentResearchRecord,
    ContentSource,
    ContentVersion,
)
from seo_engine.domain.models.decision import (
    Action,
    ActionApproval,
    ActionOutcome,
    Evidence,
    EvidenceRelationship,
    Experiment,
    Opportunity,
    Policy,
    Recommendation,
)
from seo_engine.domain.models.identity import (
    Entitlement,
    RoleDefinition,
    SubscriptionPlan,
    Tenant,
    TenantUser,
    UsageEvent,
    User,
)
from seo_engine.domain.models.integrations import (
    GA4Connection,
    GA4Conversion,
    GA4Metric,
    GA4Property,
    GSCConnection,
    GSCInspection,
    GSCPerformance,
    GSCProperty,
    GSCSitemap,
    IntegrationConnection,
    IntegrationCredential,
    ProviderRawResponse,
)
from seo_engine.domain.models.memory import (
    EMBEDDING_DIM,
    KnowledgeEdge,
    KnowledgeNode,
    Memory,
    MemoryEmbedding,
)
from seo_engine.domain.models.mission import (
    Mission,
    MissionMetric,
    MissionProgress,
    MissionTask,
    Task,
    TaskDependency,
)
from seo_engine.domain.models.observability import AuditLog, EventRecord
from seo_engine.domain.models.search import (
    Keyword,
    KeywordCluster,
    KeywordMetricRecord,
    KeywordRanking,
    KeywordVariant,
    SearchIntentRecord,
    SearchQuestionRecord,
    SERPResultRecord,
    SERPSnapshotRecord,
)
from seo_engine.domain.models.website import (
    CrawlJob,
    CrawlPageRecord,
    Page,
    PageImage,
    PageIssue,
    PageLink,
    PageSchemaBlock,
    Website,
    WebsiteScorecard,
)

__all__ = [
    "EMBEDDING_DIM",
    "Action",
    "ActionApproval",
    "ActionOutcome",
    "AgentCapabilityRecord",
    "AgentMessage",
    "AgentOutput",
    "AgentRecord",
    "AgentRun",
    "AgentToolRecord",
    "AuditLog",
    "Brand",
    "BrandAudience",
    "BrandClaim",
    "BrandCompetitor",
    "BrandGoal",
    "BrandLocation",
    "BrandProduct",
    "BrandService",
    "BrandVoiceProfile",
    "CompetitorObservation",
    "ContentAsset",
    "ContentBriefRecord",
    "ContentEvaluationRecord",
    "ContentRepair",
    "ContentRepresentation",
    "ContentResearchRecord",
    "ContentSource",
    "ContentVersion",
    "CrawlJob",
    "CrawlPageRecord",
    "Entitlement",
    "EventRecord",
    "Evidence",
    "EvidenceRelationship",
    "Experiment",
    "GA4Connection",
    "GA4Conversion",
    "GA4Metric",
    "GA4Property",
    "GSCConnection",
    "GSCInspection",
    "GSCPerformance",
    "GSCProperty",
    "GSCSitemap",
    "IntegrationConnection",
    "IntegrationCredential",
    "Keyword",
    "KeywordCluster",
    "KeywordMetricRecord",
    "KeywordRanking",
    "KeywordVariant",
    "KnowledgeEdge",
    "KnowledgeNode",
    "LLMUsage",
    "Memory",
    "MemoryEmbedding",
    "Mission",
    "MissionMetric",
    "MissionProgress",
    "MissionTask",
    "Opportunity",
    "Page",
    "PageImage",
    "PageIssue",
    "PageLink",
    "PageSchemaBlock",
    "Policy",
    "Project",
    "ProviderRawResponse",
    "Recommendation",
    "RoleDefinition",
    "SERPResultRecord",
    "SERPSnapshotRecord",
    "SearchIntentRecord",
    "SearchQuestionRecord",
    "SubscriptionPlan",
    "Task",
    "TaskDependency",
    "Tenant",
    "TenantUser",
    "UsageEvent",
    "User",
    "Website",
    "WebsiteScorecard",
]
